// Copyright 2018 The OpenPitrix Authors. All rights reserved.
// Use of this source code is governed by a Apache license
// that can be found in the LICENSE file.

// Auto generated by 'go run gen_helper.go', DO NOT EDIT.

package task

import (
	"context"

	"github.com/codefuture-io/openpitrix/pkg/constants"
	"github.com/codefuture-io/openpitrix/pkg/db"
	"github.com/codefuture-io/openpitrix/pkg/gerr"
	"github.com/codefuture-io/openpitrix/pkg/models"
	"github.com/codefuture-io/openpitrix/pkg/pi"
	"github.com/codefuture-io/openpitrix/pkg/util/ctxutil"
)

func CheckTasksPermission(ctx context.Context, resourceIds []string) ([]*models.Task, error) {
	if len(resourceIds) == 0 {
		return nil, nil
	}
	var sender = ctxutil.GetSender(ctx)
	var tasks []*models.Task
	_, err := pi.Global().DB(ctx).
		Select(models.TaskColumns...).
		From(constants.TableTask).
		Where(db.Eq(constants.ColumnTaskId, resourceIds)).Load(&tasks)
	if err != nil {
		return nil, gerr.NewWithDetail(ctx, gerr.Internal, err, gerr.ErrorInternalError)
	}
	if sender != nil {
		for _, task := range tasks {
			if !task.OwnerPath.CheckPermission(sender) && task.Owner != sender.UserId {
				return nil, gerr.New(ctx, gerr.PermissionDenied, gerr.ErrorResourceAccessDenied, task.TaskId)
			}
		}
	}
	if len(tasks) == 0 {
		return nil, gerr.New(ctx, gerr.NotFound, gerr.ErrorResourceNotFound, resourceIds)
	}
	return tasks, nil
}

func CheckTaskPermission(ctx context.Context, resourceId string) (*models.Task, error) {
	if len(resourceId) == 0 {
		return nil, nil
	}
	var sender = ctxutil.GetSender(ctx)
	var tasks []*models.Task
	_, err := pi.Global().DB(ctx).
		Select(models.TaskColumns...).
		From(constants.TableTask).
		Where(db.Eq(constants.ColumnTaskId, resourceId)).Load(&tasks)
	if err != nil {
		return nil, gerr.NewWithDetail(ctx, gerr.Internal, err, gerr.ErrorInternalError)
	}
	if sender != nil {
		for _, task := range tasks {
			if !task.OwnerPath.CheckPermission(sender) {
				return nil, gerr.New(ctx, gerr.PermissionDenied, gerr.ErrorResourceAccessDenied, task.TaskId)
			}
		}
	}
	if len(tasks) == 0 {
		return nil, gerr.New(ctx, gerr.NotFound, gerr.ErrorResourceNotFound, resourceId)
	}
	return tasks[0], nil
}
